services:
  vision:
    build:
      context: .
      dockerfile: Dockerfile-jetson
    environment:
      - DEBUG=1
      - DETECTION_TOLERANCE=15
      - ALPHANUMERIC_MODEL_STEP=1080
      - ALPHANUMERIC_MODEL_FRAME_SIZE=1280
      - ALPHANUMERIC_MODEL_ITERATIONS=12
      - ALPHANUMERIC_MODEL_CROP_AMOUNT=10
      - ALPHANUMERIC_MODEL_CONF_THRESHOLD=0.4
      - ALPHANUMERIC_MODEL_IOU_THRESHOLD=0.4
    ports:
      - "8003:8003"
    volumes:
      - .:/app/
      - /dev/shm:/dev/shm
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    logging:
      driver: loki
      options:
        loki-url: http://172.17.0.1:3100/loki/api/v1/push
    depends_on:
      - loki

  redis:
    image: "redis:alpine"
    
  prometheus:
    image: prom/prometheus:v2.51.0
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - vision
      - cadvisor

  loki:
    image: grafana/loki:2.9.2
    volumes:
      - ./loki:/etc/loki
    command: -config.file=/etc/loki/config.yaml
    ports:
      - 3100:3100

  grafana:
    image: grafana/grafana:10.2.0
    volumes:
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - vision
