global:
  scrape_interval: 3s

  external_labels:
    monitor: "vision"

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "vision"
    static_configs:
      - targets: ["vision:8003"]

  - job_name: "flight"
    static_configs:
      - targets: ["flight:8004"]
