{
 "title": "Vision Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "3s",
 "panels": [
  {
   "title": "Request Summary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_count\n",
     "legendFormat": "{{method}} {{path}}"
    },
    {
     "expr": "flask_http_request_total{status!=\"200\"}",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Images Processed and Queued",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "vision_images_processed_total", "legendFormat": "Images Processed" },
    { "expr": "vision_queue_size", "legendFormat": "Images Queued" },
    {
     "expr": "vision_images_processed_total/vision_active_time_seconds_total",
     "legendFormat": "Images Processed Per Second"
    }
   ]
  },
  {
   "title": "Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "vision_active_time_seconds_total",
     "legendFormat": "Active Time (s)"
    },
    { "expr": "vision_images_processed_total", "legendFormat": "Total Images Processed" }
   ]
  },
  {
   "title": "Average Response Time (Past 30s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"200\"}[30s])/rate(flask_http_request_duration_seconds_count{status=\"200\"}[30s])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"uas-2024-vision-1\"}[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name='uas-2024-vision-1'} / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Docker Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{compose_project=\"uas-2024\"}"
    }
   ]
  }
 ]
}