name: Docker Image Check

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker containers
      working-directory: ./vision
      run: make build
    - name: Start Docker container
      working-directory: ./vision
      run: make run
    - name: Run unit tests
      working-directory: ./vision
      run: docker exec vision-web-1 python3 -m unittest
    - name: Stop containers
      working-directory: ./vision
      run: make kill
