name: Docker Image Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker containers
      run: make build
    - name: Start Docker container
      run: make run
    - name: Run unit tests
      run: docker exec suas-onboard-vision-web-1 python3 -m unittest
    - name: Stop containers
      run: docker compose kill
